### ISSUE TITLE
Add-on not compatible with Firefox Quantum

### ISSUE THREAD

**Issue by Toukite** [fligtar/password-exporter#102]
Getting message "This add-on is not compatible with your version of Firefox."
Using Firefox Quantum 61.0.2 (64 bits), date 2018-08-28
Cannot find any way to export saved password from firefox, please update this plugin :) !!!

**Comment by jvillalobos** [comment]
Due to missing password APIs, it's not possible at the moment. Once those are implemented, we will try to port this add-on so it continues to work. See #80.
