### ISSUE TITLE
Help regarding importing passwords

### ISSUE THREAD

**Issue by junomarian** [fligtar/password-exporter#108]
Hey there! 
I am trying to import csv passwords file exported by chrome . but this addon is not accepting the format of csv file.

Chrome csv output file format is   name,url,username,password
but exporter addon format is "hostname","username","password","formSubmitURL","httpRealm","usernameField","passwordField"
how to solve this problem?
i just want all my passwords transfer from chrome to firefox.
i am on older version of firefox, which is compatible with password exporter addon.

**Comment by strawbeard** [comment]
Hi junomarian,

You can open the CSV file as an Excel table. There rearrange columns, remove extra columns and edit the field names in line #1 as required by Password Exporter. Finally save (export) the table as a CSV file and feed it to Password Exporter.

If you don't have Excel or any other spreadsheet software, you might use online CSV tools, e.g. http://convertcsv.com/csv-viewer-editor.htm, if you trust them not to store every fart that comes their way:=> I played around a bit with this service: CSV file is uploaded and displayed in tabular format; columns could be moved by drag (left border) and drop, be deleted by clicking at a cell, then right-clicking and selecting "Remove column". Line #1 is fully editable.

Maybe it's sufficient to edit just the first line, using the field names that Password Exporter expects but putting them into the sequence as the fields are stored in the data lines. Any field not to be imported would be indicated by an extra comma. I don't know wether the import function is that much flexible.

Good luck

**Comment by KB-Concepts** [comment]
Very cool of you to get back to me.  J

**Comment by jvillalobos** [comment]
Closing since this isn't a problem with the extension and it appears to be resolved.
