### ISSUE TITLE
Increase Seamonkey compatibility version number

### ISSUE THREAD

**Issue by commander-keen** [fligtar/password-exporter#19]
The extension seems to work fine until Seamonkey 2.7.1 at least. Please increase Seamonkey's compatibility version number from 2.1b1 to something more recent, to allow installation without "tricks" (e.g. manipulation the install.rdf file)
Thanks.

**Comment by jvillalobos** [comment]
SeaMonkey support was dropped.

**Comment by TeoTwawki** [comment]
> SeaMonkey support was dropped.

why was that, was there something it depends on that firefox has which seamonkey does not?

Edit: mm nope, exports all my passwords just fine with 1 little edit. Jeez.

**Comment by jvillalobos** [comment]
Lack of time for testing on other applications, essentially. I'd rather not claim support if I don't test the changes being done to the add-on, and it will probably be ported to WebExtensions soon, which SeaMonkey doesn't support.

Sorry about that. I'm glad the add-on is still working for you after changing the manifest.

**Comment by TeoTwawki** [comment]
Understandable. Going to try and maintain a seamonkey specific variant to survive beyond *"WE day" when all our 'monkey extensions are doomed.* if people try and report seamonkey bugs to you feel free to send'em my way.
