### ISSUE TITLE
No Button in Preferences with (upcoming) browser.preferences.inContent;true

### ISSUE THREAD

**Issue by theodoor** [fligtar/password-exporter#21]
Button not shown in upcoming In-Content preferences: https://wiki.mozilla.org/In-content_preferences

Involves: 
- Firefox 15 with browser.preferences.inContent set to true
- Newer versions with default settings

Update: Tab Mix Plus button is still working in in-content-preferences so you can take a peek there how it can be done.

**Comment by jvillalobos** [comment]
Fixed on version 1.3.
