### ISSUE TITLE
Impossible to export nor import any password with Firefox using Password Exporter

### ISSUE THREAD

**Issue by hd3** [fligtar/password-exporter#34]
I am using the French version of Firefox 33.0 and just installed Password Exporter. When I click Outils>Options>Sécurité>Importer/Exporter-les-mots-de-passe puis sur "Importer les mots de passe" ou "Exporter les mots de passe", absolutely nothing happens. Same thing when I do Outils>Modules complémentaires>Password Exporter>Options...

I copy above the diagnostic you asked for :

"Some basic information about this environment:
userAgent: Mozilla/5.0 (Windows NT 5.1; rv:33.0) Gecko/20100101 Firefox/33.0
Detected Firefox Version Equivalent: undefined
Detected as Thunderbird: undefined
Components:
@mozilla.org/passwordmanager;1: does not exist
@mozilla.org/login-manager;1: exists
@mozilla.org/login-manager/storage/legacy;1: does not exist
nsIPasswordManager: does not exist
nsIPasswordManagerInternal: does not exist
nsIPassword: does not exist
nsIPasswordInternal: does not exist
nsILoginManager: exists
nsILoginInfo: exists"

Thanks for your help
Sincerely
Henri

**Comment by jvillalobos** [comment]
Please try with the latest version (1.3.1). There was a localization error in the code that was probably causing the problem you described.
