### ISSUE TITLE
Password Exporter lost all passwords

### ISSUE THREAD

**Issue by spunFIN** [fligtar/password-exporter#42]
After todays update it lost ALL passwords... I had couple hundreds of them there and every single one is gone now. Using Firefox 38.0.1. :( :-1:

**Comment by jvillalobos** [comment]
Password Exporter doesn't do anything with your passwords unless you try to import them or export them, so I doubt the update to 1.3 is the cause of your problem. Did you also update Firefox or something else?

**Comment by spunFIN** [comment]
I have auto-update enabled on both of them, so I can't be sure what happened (besides that I know PE updated today). And I have never exported or imported my passwords.
Few days back I had my passwords there, and haven't installed/uninstalled etc anything new after that - tho there was some Win7 (64b Home Premium) updates also in past couple days, which forced chkdsk, so that might be the reason as I didn't see how it ended.. :F

**Comment by jvillalobos** [comment]
Yeah, I can't imagine PE being the culprit here. I'm sorry about your passwords, but I don't think there's anything that can be done here.
