### ISSUE TITLE
FF 38 No longer able to access Exporter through Tools--> Options, must to got addons entry it self.

### ISSUE THREAD

**Issue by StanWalker** [fligtar/password-exporter#43]
FF seems to have done an auto update on me even though all update options are off.

Instead of Options opening a window, it now opens as a web page - about:preferences#security

Unlike old Options window, there are now no buttons for Password Exporter in the tools menu. You must now go to Addons and click the Options button for Exporter to export or import passwords.

Can you put an entry in Tools--> Options as before or must I use Exporter via the Addons page.

Bob Novell

**Comment by jvillalobos** [comment]
Did you also disable add-on updates? Version 1.3.1 of Password Exporter should include a button in the new preferences UI.
