### ISSUE TITLE
Two Questions Regarding File Formats

### ISSUE THREAD

**Issue by KitchM** [fligtar/password-exporter#60]
If I understand it correctly, Firefox stores passwords in the key3.db and logins.json (since version 32) files, but were formerly stored in signons.txt (prior to version 2.0.0.2),  signons3.txt (Firefox 3) or signons.sqlite (Firefox 3.5) files.

Since these files are encrypted, one cannot directly read them to see the passwords.

1. Is it true that Password Manager simply acts as an interface to get the passwords into an XML or CSV format, while Firefox can natively get them into an HTML format?

2. What are the benefits of saving them in a CSV or XMl format over others?

**Comment by jvillalobos** [comment]
1. Yes, the add-on just gets the passwords and exports them in XML or CSV format.
2. The main utility of the add-on is to easily export and reimport the passwords in different Firefox profiles. XML and CSV are just convenient formats to use (though there are arguably better ones like JSON that haven't been implemented).

**Comment by KitchM** [comment]
Actually then, it is importing into JSON; just not exporting into JSON.  How do you compare these others to HTML?

**Comment by jvillalobos** [comment]
CSV and XML were just the formats originally implemented, long ago. I'm the current maintainer, but haven't had the time to implement other formats.

HTML doesn't seem like a good format to use, since it's mostly for displaying data, rather than storing it. XML is more efficient for this, and I don't expect users needing to visualize their passwords very often.

**Comment by KitchM** [comment]
I thought of HTML as you do.  I wonder why Firefox exports to it?

I also use KeePassX, and would like to be able to export right into its format and viseversa.  That way I can have a central store, see the passwords when I want and be able to put some back into FF.  That would be ideal and worth paying for.  As it is, the hodgepodge of file formats makes my head spin.
