### ISSUE TITLE
Unable to import Passwords

### ISSUE THREAD

**Issue by imkeZA** [fligtar/password-exporter#68]
Hi, 
I've been using this add on for a while and it has been fantastic. 
I needed to format my PC and exported all my passwords no problem. I formatted and reinstalled Firefox 52.0b1 (32-bit) and installed the add on and now nothing happens when I click the import or export button.
Please assist.

Thank you!

**Comment by Tusinski** [comment]
I have the same Problem! :-(

**Comment by Pafzedog** [comment]
problem should be with Firefox beta, I switched to stable version (51) and it works .

**Comment by imkeZA** [comment]
Ah ok yes, thanks for the help.

**Comment by Spearfoot** [comment]
I have the same problem with Firefox 52.0: can't export or import passwords.

**Comment by theclockman** [comment]
I have the same problem with Firefox 52.0: can't export or import passwords.

**Comment by jvillalobos** [comment]
I just uploaded version 1.3.3 to the add-ons site. It may take some time before it's published on the site. If you know how to run unsigned versions, please give it a try and let me know if the problem can still be reproduced.

**Comment by MSB1230** [comment]
I don't know how to run unlisted versions but would be happy to get from you directly and try it out

**Comment by jvillalobos** [comment]
Thanks for offering, but it was approved now and should be available via automatic updates.

**Comment by MSB1230** [comment]
The offer still stands for v 1.3.4 when you are ready.
    Thanks for the update.  It works fine now.
    
    
    On 3/12/2017 10:54 AM, Jorge Villalobos
      wrote:
    
    
      Thanks for offering, but it was approved now and should be
        available via automatic updates.
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fligtar/password-exporter","title":"fligtar/password-exporter","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fligtar/password-exporter"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jvillalobos in #68: Thanks for offering, but it was approved now and should be available via automatic updates."}],"action":{"name":"View Issue","url":"https://github.com/fligtar/password-exporter/issues/68#issuecomment-285949736"}}}
    
    
    -- 
_________________________
Mark S. Baron
Nullum Gratuitum Prandium

**Comment by jvillalobos** [comment]
Awesome, thank you. To everyone else affected by this, please report back if you run into other problems.

**Comment by stanwmusic** [comment]
It is working for me now,  Thank you!
![777](https://cloud.githubusercontent.com/assets/6845544/23884924/466c8c52-0846-11e7-8eae-39aa3acf4eb7.jpg)

**Comment by Tusinski** [comment]
Perfect!
Windows 10 - Firefox 52 64bit

Thanx 👍
