### ISSUE TITLE
Firefox v52 support

### ISSUE THREAD

**Issue by momoe** [fligtar/password-exporter#73]
Firefox has removed Netscape Plugin API except for Flash, in replacement for WebAssembly. Making existing version of Password Export unable to import/export any password information.

**Comment by jvillalobos** [comment]
Which version of the extension do you have installed? Version 1.3.3 was released over the weekend with some fixes for Firefox 52.

**Comment by momoe** [comment]
**UPDATE**
I was able to pull the latest update today and the import/export functions have resumed. TY for your work!
