### ISSUE TITLE
Cannot read exported passwords

### ISSUE THREAD

**Issue by mth021c** [fligtar/password-exporter#74]
After using password exporter, I tried to view the exported file, but nothing showed up. I used XML as I have before. Any suggestions?

**Comment by jvillalobos** [comment]
What's the size of the file? How would you normally open it?

**Comment by mth021c** [comment]
The file is 11 kb. I would normally click on it and it would open.

 

 

Dave Meltzer

 

 

-----Original Message-----

**Comment by jvillalobos** [comment]
Then the data is probably there. The problem may be the file extension, which should be .xml or .csv. If there's no file extension, the right program won't open.
