### ISSUE TITLE
unable to import .csv 

### ISSUE THREAD

**Issue by ineuw** [fligtar/password-exporter#76]
I exported the passwords from Firefox 52.0.1 (US) to simplify the removal of duplicated sites with both old and new passwords. I deleted the passwords in Firefox. Now, I am unable to import the clean .csv file. Please help to resolve this. Otherwise, I have to manually log in to some 132 sites and forums. 

This is the export & import structure:
`# Generated by Password Exporter; Export format 1.1; Encrypted: false
"hostname","username","password","formSubmitURL","httpRealm","usernameField","passwordField"

**Comment by jvillalobos** [comment]
Do you see any error messages when you try to import?

**Comment by ineuw** [comment]
No, it just did nothing and the progress bar indicated no progress, I haven't tried it since I reported it, I just restored the file from my Macrium backup. Is there anything I can do to provide more info?

**Comment by jvillalobos** [comment]
Try opening the Browser Console from the Tools > Web Developer menu and running the import again.

**Comment by jvillalobos** [comment]
... and check for any errors reported there.

**Comment by ineuw** [comment]
Thanks. Will do very soon, I must make a backup anyways.

**Comment by ineuw** [comment]
There is a problem with the import. It can't be relied upon to restore the exported data correctly. I tested it twice with the same results.

The import reported 22 records rejected but the list of rejected url's were only 20.
At best this can mean that the 22 included the header and the column names.
There are  20 rejected url's with this identical error message.

([JavaScript Error: "l.usernameField is null" {file: "resource://gre/modules/LoginHelper.jsm" line: 101}]'[JavaScript Error: "l.usernameField is null" {file: "resource://gre/modules/LoginHelper.jsm" line: 101}]' when calling method: [nsILoginManagerStorage::addLogin])

One record has no username which is a valid profile with https://duckduckgo.com cloud storage. They don't use  a username, only a password, with which they encrypt a user configuration. 
It rejected the Firefox sync login which has a long encryption string as the username.
The rest of the logins all have usernames, and are not duplicates. 
It also rejected a set of identical url's, (192.168.0.1)  one of which is the passworded login to the router and the other is the passworded WiFi access.

It is unacceptable for your add-on to make any decision on the validity of the data, be it a duplicate, or a missing username, It must import the exported data as is. Otherwise the add-on is useless.

**Comment by jvillalobos** [comment]
`LoginHelper.jsm` is a file in Firefox, not in the add-on.

At this point I'm not making any changes in the add-on until it is migrated to the new WebExtensions API, which should happen in the next couple of months. I'm sorry I can't help you with this problem now. I hope the new API will make it easier to avoid these kinds of problem.

**Comment by ineuw** [comment]
Thanks for your reply. I understand and will await the new release. Is there anything I can do about LoginHelper.jsm? Report it as a bug perhaps? or just live with it for now?

**Comment by jvillalobos** [comment]
I don't think there's much that can be done for now. Even if a change were made in Firefox code, it will take about as much time to make it to the release versions.

**Comment by ineuw** [comment]
Thanks for your trouble. I am closing this issue.

**Comment by JustOff** [comment]
The fix for this particular issue is [rather simple](https://github.com/JustOff/password-backup-tool/commit/99ea893f90e3d88633a6d0a8473bc811a3e8d389), but since this extension is most likely going to die because it can't be migrated to WebExtensions, I'm not sure if I shoud propose the solution as a pull request.

**Comment by jvillalobos** [comment]
I'll gladly take patches and push an update.

**Comment by ineuw** [comment]
Much thanks to both of you. When will this revision be available for download?

**Comment by jvillalobos** [comment]
Version 1.3.4 has this fix and is awaiting review on AMO. It should be available in a couple of weeks. Sorry for the delays on this.

**Comment by ineuw** [comment]
Thanks for your efforts. I will wait for v1.3.4 and let you know the results.

**Comment by JustOff** [comment]
> It should be available in a couple of weeks.

Weeks, really? The cobbler's children have no shoes? :stuck_out_tongue_winking_eye:

**Comment by jvillalobos** [comment]
I don't use my powers for personal benefit 😛 

Nevertheless, the update has been approved now. Let me know if it works.

**Comment by ineuw** [comment]
Hi, It works well. no problems. Thank you
