### ISSUE TITLE
Unable to import - exported password file.

### ISSUE THREAD

**Issue by sapatelbaps** [fligtar/password-exporter#78]
I exported password with and without "obfuscate" option from one profile.
But in other profile of same account when I try to import it shows below error:

**https://accounts.firefox.com ([JavaScript Error: "Cc[contractID] is undefined" {file: "jar:file:///E:/Firefox/burg34up.default/extensions/remember-passwords@stanimir-stamenkov.addons.mozilla.org.xpi!/components/nsLoginManager.js" line: 62}]'[JavaScript Error: "Cc[contractID] is undefined" {file: "jar:file:///E:/Firefox/burg34up.default/extensions/remember-passwords@stanimir-stamenkov.addons.mozilla.org.xpi!/components/nsLoginManager.js" line: 62}]' when calling method: [nsILoginManager::addLogin])**

I am unable to see saved password in the target profile. This error repeats for no. of password entries.
Is there any way to fix the issue?

**Comment by jvillalobos** [comment]
Which version of Firefox are you using? Does this happen on every import you try?

**Comment by sapatelbaps** [comment]
**I have the latest one.** Currently I am using 54.0.1 (64-bit) but this problem I am facing since 3-4 months.
That's why I attached the error log of the extension for your ref. I can see "Logins" in my mobile and all passwords are saved there since more than a year and no issue in that. 
But In my personal and company laptops' I m unable to see saved passwords since few months so I tried using this extension but no luck...!
Thanks in advance for any help.

**Comment by jvillalobos** [comment]
What do you mean with "I'm unable to see saved passwords since few months"? Were you having problems with your passwords before you started using this extension?

**Comment by sapatelbaps** [comment]
Yes. 
In company laptop the profile is old of 3 years. 
Same happened for my 1.5 year old personal laptop profile.
Passwords were showing fine since long time in both machines since beginning but before may be some 3-4 months I m unable to view saved passwords in both machines. Could be the issue in firefox update.
But in Firefox for android its working fine since 1.2years.

So, I setup a complete new profile of same account and exported all passwords in normal and obfuscate both files.
Now, when I came back to old pro profile of same account which I m using since long (3 years and 1.5year) while importing passwords using this same extension its not working.
This same extension can export passwords but unable to import - so for your ref. I provided error log. It seems some API change may be of Firefox. Its missing some required data element/field to start with as per log.

**Comment by jvillalobos** [comment]
Looking more closely at the error messages, I see those are both caused by a different add-on called Remember Passwords. So, either those error messages are unrelated to the import problem, or the Remember Passwords add-on doesn't work along with Password Exporter. I suggest that you disable that add-on and try again.

**Comment by sapatelbaps** [comment]
Yes and that worked finally. I just removed that extension and now everything is working fine.
Thanks a lot for your help.....!
