### ISSUE TITLE
Cannot Import Firefox 52

### ISSUE THREAD

**Issue by drgkt** [fligtar/password-exporter#82]
Can export, but cannot import neither csv not xml even if created by the export function.

Checked xml, no errors found.

**EDIT:** Spoke too soon.
Exported all passwords via the tool.
Erased one Firefox password entry.
Used the above CSV file to import passwords.
It DID import the one entry deleted above.

What I did before and did not work, I edited the CSV via both Notepad and Excel, erased all entries BUT the one I manually deleted from FF and saved the file under another name which in turn I fed to the tool.

Obviously the tool did not like the CSV format.

Can you please direct me to a suitable CSV editor program?
Thanks

**Comment by drgkt** [comment]
The tool can use only the cvs file that IT created itself. 
Attempts to use cvs files created in notepad or excel failed.
Which program to use to create or edit the tool's cvs file that would be compatible with the tool?

**Comment by jvillalobos** [comment]
If you're familiar with the CVS format, you can use a simple text editor like Notepad to make changes. Otherwise, programs like Excel can import and export in CVS format, though they might add a bunch of unnecessary data that needs to be removed.

**Comment by drgkt** [comment]
Unfortunately, like I said, the tool did not accept the edited (by notepad or by excel) file to import a password.
