### ISSUE TITLE
password-exporter not working with Firefox 57

### ISSUE THREAD

**Issue by MagicOwlAZ** [fligtar/password-exporter#86]
I puzzled this morning on Nov 15th, 2017. so Firefox updated itself that new version changed 57. so Firefox does not work with password exporter. I wonder. When password-exporter Version 1.3.4 last July 4th, 2017 will change new updated version? I want to know when. I can patient and wait for new version of Password Exporter.

**Comment by jvillalobos** [comment]
Due to missing password APIs, it's not possible at the moment. Once those are implemented, we will try to port this add-on so it continues to work. See #80

**Comment by appolo007** [comment]
I had to downgrade to Firefox 54 x64bits to be able continue to use Password Exporter Add-Onn. Any solution so far??
