### ISSUE TITLE
Finding a working version of Firefox.

### ISSUE THREAD

**Issue by Studcrusher** [fligtar/password-exporter#88]
**This latest update v57 does not work with 4 of my ad ons and it summarily decided to disrupt my routine with out authorization by uninstalling them.
So where is the previous version of Firefox, the one that worked just fine before they decided to fix something that wasn't broken. I want t reinstall that version. I am at a complete standstill. I even had to dig thru my history to get the url for yuckfoo to confirm my email addy. I dont want to even talk about how long it took me to find the email addy for it. 
All just so i can find out where the previous cooperative working version of Firefox is..**

**Comment by jvillalobos** [comment]
Due to missing password APIs, it's not possible at the moment. Once those are implemented, we will try to port this add-on so it continues to work. See #80
