### ISSUE TITLE
firefox 75 quantum update

### ISSUE THREAD

**Issue by nicolaemoldoveanu** [fligtar/password-exporter#92]
I use frequently you password exporter plugin for firefox
But the new version of firefox does not work anynmore with this plug in
Are there going to be any updates?
Thank you

**Comment by jvillalobos** [comment]
Due to missing password APIs, it's not possible at the moment. Once those are implemented, we will try to port this add-on so it continues to work. See #80

**Comment by nicolaemoldoveanu** [comment]
thank you very much for your fast answer! that would help a lot!
